#!/usr/bin/env python3
"""
Render THIRD_PARTY_LICENSES.md from cargo-about's JSON output.

cargo-about's default handlebars template repeats the full license text once
per text-variant per license (the Apache-2.0 license alone has ~46 slightly-
different LICENSE files among our 388 Apache-licensed crates). That produces
a 13k-line file. This script collapses to one section per license name with
a single crate list and the canonical license text.

Usage (from src-tauri/):
    cargo about generate --format json | python3 scripts/render-third-party-licenses.py > ../THIRD_PARTY_LICENSES.md
"""
import json
import sys
from collections import defaultdict


PREAMBLE = """\
# Third-Party Licenses

Ekorbia is built on top of a number of open-source Rust crates. This file
enumerates every crate that ends up in a release build of Ekorbia, grouped
by license. The canonical text for each license appears once at the end of
its section.

This file is generated by [`cargo-about`](https://github.com/EmbarkStudios/cargo-about)
with a custom renderer (`src-tauri/scripts/render-third-party-licenses.py`).
To regenerate after dependency changes:

```bash
cd src-tauri
cargo about generate --format json | python3 scripts/render-third-party-licenses.py > ../THIRD_PARTY_LICENSES.md
```

Front-end libraries (React, ReactDOM, Babel-standalone, marked, highlight.js,
DOMPurify, Google Fonts) are loaded at runtime from CDN (unpkg / Google
Fonts) and are not vendored into the repository. Their licenses live with
the upstream projects.

---

"""


def crate_link(crate: dict) -> str:
    name = crate.get("name", "?")
    version = crate.get("version", "")
    repo = crate.get("repository") or f"https://crates.io/crates/{name}"
    return f"- [`{name}` {version}]({repo})"


def main() -> int:
    data = json.load(sys.stdin)
    overview = data.get("overview", [])
    licenses = data.get("licenses", [])

    # Aggregate every crate that appears under each license, deduping by
    # (name, version) — the same crate can appear in multiple text-variant
    # buckets if cargo-about found multiple LICENSE files in its source.
    crates_by_license: dict[str, dict[tuple, dict]] = defaultdict(dict)
    for ov in overview:
        for idx in ov.get("indices", []):
            lic = licenses[idx]
            for entry in lic.get("used_by", []):
                crate = entry.get("crate", {})
                key = (crate.get("name", ""), crate.get("version", ""))
                crates_by_license[ov["name"]].setdefault(key, crate)

    out = [PREAMBLE, "## License overview\n\n"]
    for ov in overview:
        unique = len(crates_by_license.get(ov["name"], {}))
        out.append(f"- **{ov['name']}** ({ov['id']}) — {unique} crate{'s' if unique != 1 else ''}\n")
    out.append("\n---\n\n## Crates by license\n\n")

    for ov in overview:
        name = ov["name"]
        spdx = ov["id"]
        out.append(f"### {name} (`{spdx}`)\n\n")
        crates = sorted(crates_by_license.get(name, {}).values(),
                        key=lambda c: (c.get("name", "").lower(), c.get("version", "")))
        for crate in crates:
            out.append(crate_link(crate) + "\n")
        out.append("\n<details>\n<summary>License text</summary>\n\n")
        out.append("```\n")
        out.append(ov.get("text", "").rstrip() + "\n")
        out.append("```\n\n</details>\n\n")

    sys.stdout.write("".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
